name: Benchmarks

on: push

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker image
        run: docker build -t foresight-comparison -f dockerfile .

      - name: Run benchmarks (5s per benchmark)
        # CSV goes to stdout -> results.csv; logs go to stderr
        run: |
          set -euo pipefail
          docker run --rm -e BENCH_SECONDS=5 foresight-comparison > results.csv

      - name: Show CSV in job log
        run: cat results.csv

    #   - name: Upload results.csv
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: results
    #       path: results.csv

